"""Pull request creation on git platforms."""

from __future__ import annotations

import logging

from komyt.adapters.git.base import GitPlatformAdapter, PRData, PRResult
from komyt.core.models import DevelopmentPlan, TicketType
from komyt.devloop.loop import LoopResult

logger = logging.getLogger(__name__)


class PRCreator:
    """Creates pull requests from completed development loops."""

    def __init__(self, platform: GitPlatformAdapter) -> None:
        self._platform = platform

    async def create(
        self,
        plan: DevelopmentPlan,
        loop_result: LoopResult,
        repo_slug: str,
    ) -> PRResult:
        title = _build_pr_title(plan)
        body = _build_pr_body(plan, loop_result)
        labels = _build_pr_labels(plan)

        pr_data = PRData(
            title=title,
            body=body,
            head_branch=plan.branch_name,
            base_branch=plan.ticket.repo_branch,
            labels=labels,
        )

        result = await self._platform.create_pr(repo_slug, pr_data)
        logger.info("PR created: %s", result.url)
        return result


def _build_pr_title(plan: DevelopmentPlan) -> str:
    type_prefixes = {
        TicketType.FEATURE: "feat",
        TicketType.BUGFIX: "fix",
        TicketType.REFACTOR: "refactor",
        TicketType.DOCS: "docs",
        TicketType.CHORE: "chore",
    }
    prefix = type_prefixes.get(plan.contract.ticket_type, "feat")
    title = plan.ticket.title
    if len(title) > 60:
        title = title[:57] + "..."
    return f"{prefix}: {title}"


def _build_pr_body(plan: DevelopmentPlan, loop_result: LoopResult) -> str:
    parts: list[str] = []

    if loop_result.failed_count > 0:
        failed_titles = [
            s.description for s, r in zip(plan.steps, loop_result.steps, strict=False)
            if r.status.value == "failed"
        ]
        bullets = "\n".join(f"  - {t}" for t in failed_titles) or "  - (see commits)"
        parts.append(
            f"> ⚠️ **Human review needed** — {loop_result.failed_count} step(s) "
            f"did not pass verification. WIP commits were pushed so the work "
            f"isn't lost, but the following steps still need a developer:\n"
            f"{bullets}\n"
        )

    parts.append(f"## Summary\n{plan.contract.objective}")
    parts.append(f"\nCloses #{plan.ticket.external_id}")

    if plan.contract.success_criteria:
        criteria = "\n".join(f"- [x] {c}" for c in plan.contract.success_criteria)
        parts.append(f"\n## Success criteria\n{criteria}")

    steps_text = "\n".join(
        f"- {'✅' if i < loop_result.completed_count else '❌'} {s.description}"
        for i, s in enumerate(plan.steps)
    )
    parts.append(f"\n## Changes\n{steps_text}")

    parts.append(
        f"\n## Stats\n"
        f"- Steps: {loop_result.completed_count}/{len(plan.steps)} completed\n"
        f"- Tokens: {loop_result.total_tokens:,}\n"
        f"- Estimated cost: ${loop_result.estimated_cost:.4f}"
    )

    parts.append("\n---\n🤖 Generated by [Komyt](https://github.com/EmerickSalmon/komyt)")

    return "\n".join(parts)


def _build_pr_labels(plan: DevelopmentPlan) -> list[str]:
    labels = ["komyt"]
    type_label = plan.contract.ticket_type.value
    labels.append(type_label)
    return labels
