"""Pipeline run report generation."""

from __future__ import annotations

import logging
from dataclasses import dataclass

from komyt.core.models import (
    DevelopmentPlan,
    PipelineResult,
    StepStatus,
    TaskStatus,
    TicketData,
)
from komyt.devloop.loop import LoopResult

logger = logging.getLogger(__name__)


@dataclass
class RunReport:
    """Human-readable report of a pipeline run."""

    ticket: TicketData
    pipeline_result: PipelineResult
    comment_body: str


class Reporter:
    """Generates reports from pipeline results."""

    def build_report(
        self,
        plan: DevelopmentPlan,
        loop_result: LoopResult,
        pr_url: str | None = None,
        duration_seconds: float = 0.0,
    ) -> RunReport:
        status = _determine_status(loop_result, pr_url)

        pipeline_result = PipelineResult(
            ticket=plan.ticket,
            status=status,
            pr_url=pr_url,
            branch_name=plan.branch_name,
            total_steps=len(plan.steps),
            completed_steps=loop_result.completed_count,
            failed_steps=loop_result.failed_count,
            total_tokens=loop_result.total_tokens,
            estimated_cost=loop_result.estimated_cost,
            duration_seconds=duration_seconds,
            error_summary=loop_result.abort_reason or None,
        )

        comment = _build_comment(pipeline_result, plan)

        return RunReport(
            ticket=plan.ticket,
            pipeline_result=pipeline_result,
            comment_body=comment,
        )


def _determine_status(loop_result: LoopResult, pr_url: str | None) -> TaskStatus:
    if loop_result.aborted:
        return TaskStatus.FAILED
    if loop_result.all_succeeded and pr_url:
        return TaskStatus.COMPLETED
    if loop_result.failed_count > 0:
        return TaskStatus.FAILED
    return TaskStatus.COMPLETED


def _build_comment(result: PipelineResult, plan: DevelopmentPlan) -> str:
    parts: list[str] = []

    if result.status == TaskStatus.COMPLETED:
        parts.append("**Komyt — Run Complete** ✅")
    else:
        parts.append("**Komyt — Run Failed** ❌")

    parts.append(
        f"\n| Metric | Value |\n"
        f"|--------|-------|\n"
        f"| Steps | {result.completed_steps}/{result.total_steps} completed |\n"
        f"| Tokens | {result.total_tokens:,} |\n"
        f"| Cost | ${result.estimated_cost:.4f} |\n"
        f"| Duration | {_format_duration(result.duration_seconds)} |"
    )

    if result.pr_url:
        parts.append(f"\n**Pull request:** {result.pr_url}")

    if result.error_summary:
        parts.append(f"\n**Error:** {result.error_summary}")

    if result.status == TaskStatus.FAILED and result.failed_steps > 0:
        failed_steps = [
            s for s in plan.steps if s.status == StepStatus.FAILED
        ]
        if failed_steps:
            parts.append("\n**Failed steps:**")
            for s in failed_steps:
                errors = "; ".join(s.error_log[:2]) if s.error_log else "unknown"
                parts.append(f"- {s.description}: {errors}")

    parts.append(
        "\n---\n🤖 Generated by [Komyt](https://github.com/EmerickSalmon/komyt)"
    )

    return "\n".join(parts)


def _format_duration(seconds: float) -> str:
    if seconds < 60:
        return f"{seconds:.0f}s"
    minutes = int(seconds // 60)
    secs = int(seconds % 60)
    return f"{minutes}m {secs}s"
